[project]
name = "appl-veil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyobjc-framework-avfoundation>=11.0",
    "pyobjc-framework-quartz>=11.0",
    "pyobjc-framework-screencapturekit>=11.0",
]
